### ISSUE TITLE
Unable to intercept downloads under Ubuntu 20.04

### ISSUE THREAD

**Issue by raidenii** [jc3213/download_with_aria2-firefox#11]
Hi,

I'm trying to set the addon to intercept downloads with Firefox under Ubuntu, but was unable to do so. Basically, downloading any file still trigger the native download manager of Firefox its own, instead of Aria2.

Tried both Firefox 84 and Firefox ESR 78 with latest addon R3700, Aria2 connects fine and Options->Download->Capturing is set to "Always". Tried to use fresh Firefox profile and just install the addon, but still fails. Developer console doesn't say anything during the download.

**Comment by raidenii** [comment]
It's weird that FF starts its native download first then get transferred to Aria2.

**Comment by jc3213** [comment]
That's Firefox's problem. You can read the discussion here. https://github.com/jc3213/download_with_aria2-chromium/issues/1#issuecomment-643772928

I've optimized the code as I can to reduce the affection. My operation here is
1) Change preference, let `Firefox` Ask me where to download
2) Download window prompt when I click on URL
3) Wait for some time, nothing in download folder
4) Click `Save` (I have only `Save` and `Cancel` on the prompt) and choose the folder to download
5) Download is cancelled and removed from the History and passed to Aria2, I can't see if file is downloaded cause I'm using Ramdisk for Testing
