### ISSUE TITLE
从连接的download属性获取文件名

### ISSUE THREAD

**Issue by Mapaler** [jc3213/download_with_aria2-firefox#14]
希望能从连接的download属性获取设定的文件名，现在只能获取原本的文件名，对于原本文件名只是时间戳的公司系统就难用了。
![Screenshot_2021-01-11-12-31-44](https://user-images.githubusercontent.com/6565860/104147587-ea766a80-5409-11eb-8f38-90e1a0b55373.png)

**Comment by jc3213** [comment]
推荐直接使用抓取功能，抓取特定后缀即可。

**Comment by Mapaler** [comment]
抓取功能是强制将浏览器的“保存”重定向到本扩展吗？

可否实现这样的形式（概念图）区分真正的浏览器保存与本程序的抓取呢？
![Screenshot_2021-01-12-20-04-33](https://user-images.githubusercontent.com/6565860/104312543-b7b79980-5511-11eb-9329-00e36c14694b.png)

**Comment by jc3213** [comment]
希望你在提出issue前能稍微测试一下本扩展的基础功能。

因为考虑到数字域名，因此我把规则改成了匹配完整的主机名。通过设置`抓取`->`总是`，或者`抓取`->`基于条件`->`监视主机名`->`192.168.48.18` 即可实现完全自动化地将来自主机名 192.168.48.18 的下载转发到Aria2 RPC上。

**Comment by Mapaler** [comment]
您好，我用这个网站只是想到这一点，因此做了演示，也可能有其他任意网站存在这样的情况，按条件用域名来匹配不太合适。
而如果设定为“总是”，则会遇到一些强认证的下载失败的问题。

因此手动选择是否通过Aria2下载还是有需求的。希望可以让右键菜单的“通过Aria2下载”能预先读取`download`值。
或者像[Aria2-Integration](https://github.com/RossWang/Aria2-Integration)一样添加抓取的快速开关按钮，方便下载失败时快速切换，目前的“抓取"设置层级太多。

**Comment by jc3213** [comment]
我对扩展添加新下载时支持了Object对象，只要是通过Stringify的Object，都可以直接添加进下载。也因此你可以试试用简单的脚本去实现直接复制出符合格式的内容。目前支持`{url, filename, folder}` 三个变量，而`referer`目前需要用户直接在下载界面输入。

**Comment by Mapaler** [comment]
请问在哪里有示例的用法吗？

**Comment by jc3213** [comment]
可以参考AMO的示例图。代码格式为
```javascript
{"url":"https://myweb.com/123.jpg","filename":"图片.jpg","folder":"D:\\Download"}
```

**Comment by jc3213** [comment]
作为相关功能我稍微引用一下 https://github.com/jc3213/download_with_aria2-firefox/issues/18

理论上通过`content_script`是可以获取超链接的`download`属性，以及直接获取`referer`与`cookie`，但是在 #18 中我提过，这个方案无法兼容于 `新任务窗口` 中的 `Referer` 设置。

再一个可能就是这个方法可能比通过`browser.tabs.query()`获取`referer`延迟更高，更容易产生双重下载的问题。并且这个方法依然无法避免延迟xx秒后自动下载的页面正确获取`referer`

还有就是，将`background`跟`新任务窗口`获取`referer`与`cookie`的方法完全独立开，整合的话也会比较麻烦。因此理论上这类问题不会给与额外的修复。

PS：如果有兴趣自己维护的话，可以自行修改 #18 中我发出来的那个 hotfix 去获取`download`属性。

**Comment by Mapaler** [comment]
还没研究过这个级别的语言，自己搞不来的。
