### ISSUE TITLE
无法修改部分设置

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2-firefox#16]
![图片](https://user-images.githubusercontent.com/2649544/116841954-63920b80-ac0d-11eb-9a95-50a30f0058a1.png)
导入导出按钮偶尔可以点击，大多数时候无法点击，不清楚原因。

文件大小的设置则完全无法修改。

Firefox 88
扩展2.4810版

**Comment by jc3213** [comment]
文件大小无法设置是因为火狐的`downloadItem.filesize`返回`-1`，详细请阅读
https://github.com/jc3213/download_with_aria2-chromium/issues/1
https://github.com/jc3213/download_with_aria2-firefox/issues/2
https://github.com/jc3213/download_with_aria2-firefox/issues/6

至于导出功能，无法点击这点我这边无法复现。请给出具体的复现步骤

**Comment by ivysrono** [comment]
我需要确定如何能复现，等两天。
![图片](https://user-images.githubusercontent.com/2649544/116888680-55b8a680-ac5e-11eb-9505-b64ed139d049.png)
这里的样式要不要改进下

**Comment by jc3213** [comment]
1） 筛选条件是独立的，而非互相包含。这意味着只要满足其中任何一个条件，下载都会被抓取。当然，判断的优先级为 功能开关 > 无视域名 > 监听域名 > 文件后缀 > 文件大小（火狐版本不支持）。
2） 这个应该是CSS样式的问题，但我看你整体界面都不正常，是否使用了缩放？如果有，还原默认缩放倍率是否会恢复正常？

**Comment by ivysrono** [comment]
没用缩放。回头我来看看怎么改css能解决。

**Comment by jc3213** [comment]
我这边已经在着手修复css相关的问题了。看了下火狐这边跟Chromium的渲染结果差别太大，麻烦耐心等待。

**Comment by ivysrono** [comment]
既然如此还是建议在火狐版本中隐藏文件大小的选项

**Comment by jc3213** [comment]
如果需要隐藏界面的话可以自己通过css隐藏，我这边就不做过多修改了。

修复已推送，AMO晚些时候上传（网络波动）。

**Comment by ivysrono** [comment]
更新后问题都解决了。
非常感谢，这是我目前找到的唯一一个能解决网易邮箱附件中文名乱码问题的Aria2扩展。
