### ISSUE TITLE
Firefox仅设置忽略主机名后所有的都不抓取了

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2-firefox#17]
https://github.com/jc3213/download_with_aria2-firefox/issues/16#issuecomment-831919795

![图片](https://user-images.githubusercontent.com/2649544/117098997-99b4c400-ada2-11eb-9236-aad86e4aea5e.png)

**Comment by jc3213** [comment]
没有设置抓取条件的前提下默认是不抓取下载的。

**Comment by ivysrono** [comment]
那如果我需要匹配所有主机仅排除baidu.com呢？
或者我要匹配其他几乎所有类型仅排除某种类型文件呢？

**Comment by jc3213** [comment]
理论上可以做到，但是同时设置文件后缀，主机名，文件大小（火狐因为本身的问题无法支持）已经能覆盖大多数使用场景了。

**Comment by ivysrono** [comment]
算了，不是Bug就好，只是现有说明令我迷惑了。
真有需要的时候就临时关闭吧。
谢谢。

**Comment by jc3213** [comment]
如果你有阅读上一个issue的引用的话，你会发现火狐本身的机制导致了如果匹配条件消耗过多的性能，会出现二次下载现象——即火狐本身下载了文件，Aria2也下载了文件。这现象的出现取决于文件的大小与你的网速，还有就是匹配消耗的时间。这也是我尽量简化匹配流程的原因。
