### ISSUE TITLE
无法在安装火狐官方扩展《多账户容器》后正确获取Cookie

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2-firefox#18]
[简介容器功能 | Firefox 帮助](https://support.mozilla.org/zh-CN/kb/%E7%AE%80%E4%BB%8B%E5%AE%B9%E5%99%A8%E5%8A%9F%E8%83%BD)

一旦在容器标签页内需要登录才能下载，抓取下载后要么出现403等错误，要么下载下来一个20k左右的文件，文件名正确但内容错误。

如果是普通标签页就没问题，当然我还没有测试隐私模式。

实测下来，常见网易邮箱会出现这个问题。还有些内部站点无法提供测试。

**Comment by jc3213** [comment]
如果可以的话，请在background.js的29行
https://github.com/jc3213/download_with_aria2-firefox/blob/4fec5e65ef694b3abb667f76e424eb3e73ce1b0e/background.js#L28
后面添加
```console.log(session)```
协助我进行debug。

**Comment by ivysrono** [comment]
经测试，与正常标签相比，容器标签变化值如下：
```
  "referer": null,
  "mime": null,
  "bytesReceived": 0,
  "totalBytes": -1,
```

**Comment by jc3213** [comment]
我希望知道的是`session`与`item`的对比结果……

另外，这也可能与`common.js`中获取Cookies的部分有关。可能因为容器问题导致无法正确获得对应的Cookies

**Comment by jc3213** [comment]
做了个临时的hotfix，至少我测试QQ邮箱没问题了，但是这个方法太粗糙，我个人极度不推荐这么做
[download_with_aria2-firefox-r4900_with_hotfix.zip](https://github.com/jc3213/download_with_aria2-firefox/files/6449041/download_with_aria2-firefox-r4900_with_hotfix.zip)

**Comment by jc3213** [comment]
经测试，这个问题是在安装 多账号容器 后，火狐的 `browser.cookies.getAll()` API无法获取 Cookie 造成的。唯一的修复方案是通过 `content_script` 进行响应，但是这个方案并不兼容扩展的全部功能，我个人推荐你去找 Mozilla 反馈问题。

我还是做了个hotfix，希望能派上用场。你可以自行 fork 后根据我的修改做后续维护，我不会继续维护这个hotfix版本。
[download_with_aria2-firefox-r4900_with_hotfix.zip](https://github.com/jc3213/download_with_aria2-
firefox/files/6449063/download_with_aria2-firefox-r4900_with_hotfix.zip)

**Comment by Mapaler** [comment]
如果属于火狐的bug的话，可以在 https://bugzilla.mozilla.org/home 反馈。我之前都发现了一个去反馈了，结果已经有人先反馈了。

**Comment by ivysrono** [comment]
反馈是可以，但我不觉得自己能用英语说清楚这个问题和需求。

**Comment by jc3213** [comment]
我在迁移至manifest v3的测试中发现，如果不给`<all_urls>`权限，那么则无法获取cookies，或许多账号容器也需要某些额外的权限？我最近在忙于迁移至manifest v3，不知道能否帮忙看下多账号容器扩展的manifest，看看里面的`permissions`相关都有些什么？

**Comment by jc3213** [comment]
目前已修复。顺便才发现r5600把contextmenu搞坏了。赶快推送吧OTL

**Comment by ivysrono** [comment]
很神奇的是我居然没传6500

**Comment by ivysrono** [comment]
6600似乎还是无效，看了下代码，是不是没有区分大小写的问题，我改的id是 `downloadWithAria2`

**Comment by jc3213** [comment]
迁移至manifest v3需要修改storage结构。（虽然已经做了测试版，但是莫名其妙会假死）

同时我还想更改jsonrpc相关的东西，让`background`抓取主要信息，然后popup以及taskMgr更多的是与background交互而非跟aria2rpc交互。较少aria2rpc的负荷，避免多个请求同时并发。

这里选用`runtime.connect`还是`runtime.sendMessage`及runtime.onMessage`让我有点尴尬。至少`runtime.sendMessage`判断交互时都塞在`runtime.onMessage`事件下面感觉有点蛋疼。而`runtime.connect`则会有多个频道……反正再研究吧。

**Comment by jc3213** [comment]
> 6600似乎还是无效，看了下代码，是不是没有区分大小写的问题，我改的id是 `downloadWithAria2`

你指啥无效？右键菜单吗？下面有个`contextMenus.onClicked`事件，里面的`contextMenuId`要对应上

**Comment by ivysrono** [comment]
容器标签页里还是不能正确获取cookie

**Comment by jc3213** [comment]
https://github.com/jc3213/download_with_aria2-firefox/blob/305624395dbf8e3fb98c524af941b4fdac7e9d3a/components/main.js#L93

这后面加个log，看看`options`的结果？我自己测试是没问题的。然后就是
https://github.com/jc3213/download_with_aria2-firefox/blob/305624395dbf8e3fb98c524af941b4fdac7e9d3a/components/main.js#L124
看下`storeId`是否正常？

**Comment by jc3213** [comment]
哦，我看到问题了
https://github.com/jc3213/download_with_aria2-firefox/blob/305624395dbf8e3fb98c524af941b4fdac7e9d3a/components/main.js#L87

这里`storeId`的d没了导致的……因为修改这里的时候我是直接web上改的，OTL

**Comment by ivysrono** [comment]
确实应该是修复了。
话说不知道哪个版本开始，好像有些无法自动接管了，比方说
https://sourceforge.net/projects/xiaomi-eu-multilang-miui-roms/files/xiaomi.eu/MIUI-STABLE-RELEASES/MIUIv12/
https://f-droid.org/packages/org.fdroid.fdroid/

**Comment by ivysrono** [comment]
确实应该是修复了。
话说不知道哪个版本开始，好像有些无法自动接管了，比方说
https://sourceforge.net/projects/xiaomi-eu-multilang-miui-roms/files/xiaomi.eu/MIUI-STABLE-RELEASES/MIUIv12/
https://f-droid.org/packages/org.fdroid.fdroid/

**Comment by jc3213** [comment]
sourceforge等问题理论上是解决不了的。因为`downloadItem.referrer`为`""`空，然后通过`tabs.query()`获取当前激活的标签页地址。这时候如果你切换了标签页导致离开了sourceforge去了其他网站，获取到的`tab.url`不匹配，自然会出错。只能说不管`chrome`还是`firefox`这里都很奇葩

**Comment by ivysrono** [comment]
好吧，f-droid总算是直链就通过右键解决吧

**Comment by jc3213** [comment]
> 好吧，f-droid总算是直链就通过右键解决吧

理论上通过webRequest似乎能解决，我记得webRequest的记录里面有`url,referrer,tabId`，我现在计划了太多东西，今天只准备改好`message`部分，游戏开新活动还要肝，感觉人秃了

**Comment by ivysrono** [comment]
不急不急，悠着点

**Comment by ivysrono** [comment]
> 
> 
> sourceforge等问题理论上是解决不了的。因为`downloadItem.referrer`为`""`空，然后通过`tabs.query()`获取当前激活的标签页地址。这时候如果你切换了标签页导致离开了sourceforge去了其他网站，获取到的`tab.url`不匹配，自然会出错。只能说不管`chrome`还是`firefox`这里都很奇葩

试了下隔壁的 https://addons.mozilla.org/zh-CN/firefox/addon/aria2-extension/
能抓取但都报错无法下载。

**Comment by jc3213** [comment]
他这个是完全基于原版，只是用Vuejs框架重写了一遍罢了……不太知道他到底对原版做了多少修改，原版得抓取逻辑是要满足抓取大小后才匹配其他规则。不知道是作者代码得问题还是啥，至少对我来说是抓取了个空气
