### ISSUE TITLE
Get "Referer" and "Cookie" via content_script | 通过content_script获取"Referer与"Cookie

### ISSUE THREAD

**Issue by jc3213** [jc3213/download_with_aria2-firefox#19]
我制作了一个通过content_script获取 Referer 与 Cookie 的新版本，我不确定这个版本是否存在双重下载问题。这个版本意在解决 #18 ，并且为后续功能提供空间——比如通过快捷键直接利用Aria2下载 URI。欢迎提供使用感想与建议。

==================================================================================

I've made a new version that uses `content_script` to retrieve Referer and Cookie for downloads (in background.js) in order to solve #18 . I'm not sure if this version will cause double download problem. The implement will provide additional function such as use hotkey to click on URI to download with aria2 instantly. Feed back and suggestions are welcomed.

==================================================================================

[download_with_aria2-firefox-r4995.zip](https://github.com/jc3213/download_with_aria2-firefox/files/6449426/download_with_aria2-firefox-r4995.zip)

==================================================================================

@CrendKing @ivysrono @Mapaler

**Comment by ivysrono** [comment]
测了下：

- zip里面套了一层文件夹，导致无法直接载入zip。这是个小问题。
- 未发现双重下载的问题。
- 网易邮箱附件等在容器标签页已经能正确下载。
- 在一个内网，amo版在容器标签页抓取有问题，现在普通标签页也不抓取了，当然问题也算是解决了。
- 其实对付内网我有个建议，就是加个选项：通过IP而非域名访问的网站一律不抓取。当然如果这也有可能增加判断成本导致双重下载，那就忽略吧。

**Comment by jc3213** [comment]
> * 在一个内网，依然有问题，建议加入需要的调试输出供测试反馈。
能否给与具体的描述，扩展设置（如监听域名），以及期往的动作

**Comment by ivysrono** [comment]
> 
> 
> > * 在一个内网，依然有问题，建议加入需要的调试输出供测试反馈。
> 
> 能否给与具体的描述，扩展设置（如监听域名），以及期望的扩展动作

选项只改了抓取为“总是”。

#18 里不是隔了两段 console.log 么，现在你改了判断模式，我也不知道需要在哪里加控制台输出了。

**Comment by jc3213** [comment]
`components/common.js`73行前面增加
```console.log(session.url , options)```

另外，内网的问题你依然没有说明具体错误……

**Comment by ivysrono** [comment]
内网情况变糟了：
测试版普通标签页获取文件大小：196
```
http://IP/weaver/weaver.file.FileDownload?fileid=a…longto_userid=422&f_weaver_belongto_usertype=0&fromrequest=1
{
  "header": [
    "Cookie: languageidweaver=7",
    "Referer: http://IP/spa/workflow/static4form/index.html?_rdm=1620624670104#/main/workflow/req?requestid=597061&isovertime=&_key=zt0bwy",
    "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/86.0"
  ],
  "out": "8.pdf"
}
```

amo版普通标签页获取文件大小：594.8k
```
{
  "url": "http://IP/weaver/weaver.file.FileDownload?fileid=a428d6e3ee0771058702939df452f02a787ba8fc9c5411b4db080a14148818437f2c1b3e18b74545b3987a440244a0aecced1b6b56a88ec1e&download=1&requestid=597061&desrequestid=0&authStr=dmlld0NoYWluPTU5NzA2MXxtYWluaWQ9NTk3MDYxfA==&authSignatureStr=02fb018e8bb058dd543767183220f0bc&f_weaver_belongto_userid=422&f_weaver_belongto_usertype=0&fromrequest=1",
  "filename": "8.pdf",
  "folder": "D:\\Down\\",
  "referer": "http://IP/spa/workflow/static4form/index.html?_rdm=1620624670104#/main/workflow/req?requestid=597061&isovertime=&_key=zt0bwy",
  "host": "IP"
}
{
  "id": 25,
  "url": "http://IP/weaver/weaver.file.FileDownload?fileid=a428d6e3ee0771058702939df452f02a787ba8fc9c5411b4db080a14148818437f2c1b3e18b74545b3987a440244a0aecced1b6b56a88ec1e&download=1&requestid=597061&desrequestid=0&authStr=dmlld0NoYWluPTU5NzA2MXxtYWluaWQ9NTk3MDYxfA==&authSignatureStr=02fb018e8bb058dd543767183220f0bc&f_weaver_belongto_userid=422&f_weaver_belongto_usertype=0&fromrequest=1",
  "referrer": "http://IP/spa/workflow/static4form/index.html?_rdm=1620624670104#/main/workflow/req?requestid=597061&isovertime=&_key=zt0bwy",
  "filename": "D:\\Down\\8.pdf",
  "incognito": false,
  "danger": "safe",
  "mime": "application/pdf",
  "startTime": "2021-05-10T05:32:07.970Z",
  "endTime": null,
  "state": "in_progress",
  "paused": false,
  "canResume": false,
  "error": null,
  "bytesReceived": 609118,
  "totalBytes": -1,
  "fileSize": -1,
  "exists": false
}
Cookie: ecology_JSessionId=sss; JSESSIONID=sss; languageidweaver=7;
```

**Comment by jc3213** [comment]
#18 中的那个版本能否正常使用？

**Comment by ivysrono** [comment]
状况有些奇怪了。
amo版有问题的是另外一个内网，这个内网amo版和hotfix版都可以正常使用。
`r4995`版我在`console.log(session.url, options);`下面又加了一行`console.log(document.cookie);`，结果输出是：`<empty string>`。
而我在内网页面打开控制台直接输入`document.cookie`得到的是`languageidweaver=7`和`r4995`一样。

**Comment by jc3213** [comment]
因为这个是`background`脚本通过document.cookie是无法获取前台（网页）的cookie的，必须通过`cookies.getAll()` API来获取。

而生成后的Cookie内容在options这个对象的header子集里面，这个结果跟前台（网页端）控制台输入 `document.cookie` 得到的可能存在出入。例：QQ邮箱通过API获取有52个，document.cookie获取只有47个。

大概就是利用content_script单纯的获取`Cookie`可能因为不完整而导致内网握手失败。但即使不完整的Cookie也胜过没有Cookie可以在 #18 多账户容器中使用。

这么看来，最终还是需要Mozilla方面来解决 多账户容器 中无法通过 `cookies.getAll()` API来获取Cookie的问题。或者有别的更有效的方案绕过去。

目前只能暂时通过非常不和谐的hotfix版本去操作。

**Comment by ivysrono** [comment]
其实我想来想去，目前状况下，最佳hotfix方案还是优化基于条件的抓取模式。
现在默认是文件大小0为禁止抓取，可以考虑默认设置成-1为禁止抓取，0为抓取全部，这样在不改变默认设置的情况下，让Firefox用户有了抓取全部排除个别站点的可能。
如此我只要排除内网适用就行了。
当然还有个方案是提供选项，排除所有IP地址直接访问的站点抓取，或者排除所有http:非https:链接的抓取。

**Comment by CrendKing** [comment]
如果Capture设成Always, 下载Ubuntu ISO没有双重下载。下载Outlook.com附件有双重下载。AMO和这个版本的行为一模一样，没有区别。

**Comment by jc3213** [comment]
> 如果Capture设成Always, 下载Ubuntu ISO没有双重下载。下载Outlook.com附件有双重下载。AMO和这个版本的行为一模一样，没有区别。

你的火狐下载设置如何？是否有设置成总是询问你下载位置，还是设定了固定的下载位置？有试过切换选项吗？我这边设置总是询问，貌似除了抓取失败外几乎没遇到过双重下载

**Comment by jc3213** [comment]
> 其实我想来想去，目前状况下，最佳hotfix方案还是优化基于条件的抓取模式。
> 现在默认是文件大小0为禁止抓取，可以考虑默认设置成-1为禁止抓取，0为抓取全部，这样在不改变默认设置的情况下，让Firefox用户有了抓取全部排除个别站点的可能。
> 如此我只要排除内网适用就行了。
> 当然还有个方案是提供选项，排除所有IP地址直接访问的站点抓取，或者排除所有http:非https:链接的抓取。

参考上面 https://github.com/jc3213/download_with_aria2-firefox/issues/19#issuecomment-836277565 办法可以规避双重下载，我正在朝你说的方向优化抓取设置。仅需要修改不太多的东西即可实现

![Capture Ignored](https://user-images.githubusercontent.com/8744936/117623959-f94a0f80-b1a6-11eb-87d0-ec84426410be.png)

**Comment by jc3213** [comment]
@ivysrono 麻烦测试一下最新的Master代码？
@CrendKing 试试`总是询问我下载位置`能否解决双重下载的问题？

**Comment by CrendKing** [comment]
> @CrendKing 试试总是询问我下载位置能否解决双重下载的问题？

我的设置就是如此。

**Comment by ivysrono** [comment]
master432似乎没有解决容器标签页的问题？

**Comment by jc3213** [comment]
> master432似乎没有解决容器标签页的问题？

并没有……因为那个解决方案并不合理

**Comment by jc3213** [comment]
> > @CrendKing 试试总是询问我下载位置能否解决双重下载的问题？
> 
> 我的设置就是如此。

我又测试了下，必须火狐的下载位置与Aria2的下载文件夹一样才不会出现二次下载问题。

**Comment by jc3213** [comment]
很好，我用手机APP，火狐扩展得到的二次验证码都无法登陆火狐账号了，直接提示我无效的二次验证码。我现在已经被隔离了，投降。

**Comment by jc3213** [comment]
很好，我用手机APP，火狐扩展得到的二次验证码都无法登陆火狐账号了，直接提示我无效的二次验证码，恢复代码也不知道扔哪去了，我现在已经被隔离了，投降。

![fuck firefox](https://user-images.githubusercontent.com/8744936/117642432-d543f980-b1b9-11eb-8823-8edc375b078b.png)

**Comment by jc3213** [comment]
> bugzilla？我还能进去，也没有要二次验证码。

我是之前莫名其妙开了二次验证码，然后上一次版本更新就各种登陆不进去。后来用Auth Plus扩展扫码进去了。问题是现在不管手机也好，Auth Plus也好都进不去，查了Mozilla的问券完全无解。只能说缘分至此了。

以后AMO版本除非哪天我心血来潮装个npm，否则几乎无解了。（幸好留了JWT的user跟token）

**Comment by jc3213** [comment]
给个链接

**Comment by ivysrono** [comment]
https://github.com/KeeTrayTOTP/KeeTrayTOTP/releases
https://post.smzdm.com/p/713042/

**Comment by jc3213** [comment]
> https://github.com/KeeTrayTOTP/KeeTrayTOTP/releases
> https://post.smzdm.com/p/713042/

原来要安装完整的Keepass，我现在的问题是，还有当初扫码的二维码，就是不管怎么操作都登陆，永远是无效的验证码（当初也是这样，后来换扩展莫名其妙好了）。算了吧……

**Comment by ivysrono** [comment]
https://support.mozilla.org/zh-CN/kb/%E7%94%A8%E4%B8%A4%E6%AD%A5%E9%AA%8C%E8%AF%81%E4%BF%9D%E6%8A%A4%E4%BD%A0%E7%9A%84%20Firefox%20%E8%B4%A6%E6%88%B7
推荐了 https://keepassxc.org/download/
大概就是不用装插件了。
如果你不更新了，能不能授权我发布在amo上？我有多台设备间同步的需求。

**Comment by ivysrono** [comment]
https://support.mozilla.org/zh-CN/kb/%E7%94%A8%E4%B8%A4%E6%AD%A5%E9%AA%8C%E8%AF%81%E4%BF%9D%E6%8A%A4%E4%BD%A0%E7%9A%84%20Firefox%20%E8%B4%A6%E6%88%B7
推荐了 https://keepassxc.org/download/
大概就是不用装插件了。
如果你不更新了，能不能授权我发布在amo上？我有多台设备间同步的需求。

**Comment by jc3213** [comment]
> https://support.mozilla.org/zh-CN/kb/%E7%94%A8%E4%B8%A4%E6%AD%A5%E9%AA%8C%E8%AF%81%E4%BF%9D%E6%8A%A4%E4%BD%A0%E7%9A%84%20Firefox%20%E8%B4%A6%E6%88%B7
> 推荐了 https://keepassxc.org/download/
> 大概就是不用装插件了。
> 如果你不更新了，能不能授权我发布在amo上？我有多台设备间同步的需求。

代码会继续更新，但是AMO这个我多半没解了，你给我的推荐的我也都试过了，还是没用……多半需要激活那会的二维码。

PS：如果你愿意发布到AMO我没任何意见，就是需要注意ID啥的。

**Comment by ivysrono** [comment]
https://addons.mozilla.org/firefox/addon/download-with-aria2/

应该不支持Android版吧？

**Comment by Mapaler** [comment]
> 
> 
> 算了，Android上需要用Aria2的情景太少了。

可以用来批量下载图片？https://www.bilibili.com/video/BV11t4y1Q71Z/

**Comment by jc3213** [comment]
增加了可修改部分Aria2全局设置的功能
需要通过设置点击 JSONRPC 设置下面的`⚙`进入

**Comment by ivysrono** [comment]
已经修复了？

**Comment by jc3213** [comment]
> 已经修复了？

刚推送了最新的代码，把上面说的问题也修复了（就是高度从某个固定值换成了`max-content`）就恢复了

**Comment by ivysrono** [comment]
同步到amo了

**Comment by jc3213** [comment]
@ivysrono 你能不能试试`不发布`单纯把现在新的代码上传至AMO检查，看看与`innerHTML`相关的报告有几个？之前的话`popup/js.js`大概有3个错误。现在只使用了2次，1次是用来显示时间，1次是拿来清空stopped列表。
而`modules/taskMgr/js.js`的话，大概也是2个？

**Comment by ivysrono** [comment]
R5800 3个
![图片](https://user-images.githubusercontent.com/2649544/120088286-8555b400-c121-11eb-897c-3a8e75ccffb3.png)

**Comment by jc3213** [comment]
看来清理任务列表的 `innerHTML = ''` 不会出警告。也就是说只是完全禁止动态值。`taskMgrWindow`那边我也准备脱掉`innerHTML`的使用就是了。

其实我尝试了很多次脱离innerHTML，目前通过`<template>`然后`cloneNode`的方式我就尝试过好几次。应该说前面准备不足，知识不够，或者说思路没转过来。在做`Tabbing`的时候各种遇到问题。简直头皮发麻。这次终于脱离了，也算是解脱了。

不过因为时间格式目前还在使用，在我想出更优解之前暂时搁置吧。而`taskMgrWindow`那边我准备脱离`<table>`但是脱离后格式对齐完全做不好了…………

前几天我正在重感冒（打完疫苗一周左右就感冒了，又不敢吃药，害怕影响疫苗效果）带病改代码，出了不少问题（比如5700——其实这个版本正常，5710继续分离文件、5720有问题，5730正常）。给你添麻烦了

**Comment by ivysrono** [comment]
R5900 就这两个了。
原来 innerHTML 还能这样脱离，学到了。
感冒还代码，是真爱啊。

**Comment by jc3213** [comment]
难受才想找点事做啊……现在鼻子不头晕了，但是说话声音还不对（鼻音），嗓子不舒服（咽炎后续症状），咳嗽还没好外，几乎没啥问题了。

我第一次就是template方案，因为把所有任务塞在一个`div`下面，按照进行状态切换的时候遇到不少问题，而且那时候删除任务/暂停任务这两个按钮也有BUG。

后来尝试用iframe做，这次做的相对成功，但是iframe实在太吃性能了。任务一多卡出翔。

然后又换回template试了次，又因为切换问题碰壁，并且按钮也有bug。

这次我保留了不少原本的活动模式（不停的把任务append到对应的`div`中），最开始那两个按钮也碰壁了，后来改了变量，从`result.status`改成了`task.status`，然后像原来一样实时修改`task.status = result.status`，解决了按钮问题，以及任务切换问题后，所有问题迎刃而解。真说还是思路转过来了。

然而这次针对`taskMgrWindow`我是真的麻木了，完全不知道怎么修改，目前就只有这个雏形想法。如果有别的参考意见也好。反正，尬住了……

**Comment by ivysrono** [comment]
最近有限的代码时间主要用来写一个自用的文档格式转换的封装了，把 pandoc xpdf LibreOffice 合到一起，迭代子文件夹转换自己常用的文本格式，实在没啥精力搞浏览器。
回头有空了按照你这个思路我来试试把几个自用扩展做出设置界面来。

**Comment by jc3213** [comment]
按理说储存设置最好用`storage`API，但是我觉得实在太复杂了就放弃了。chrome现在在推manifest v3，结果我尝试移植过去，至少`downloads`API跟`contextMenu`API似乎都没生效……

最终结果就是只有`popup`活着，`background.js`里面的功能全线阵亡（通过`popup`的`newTaskWindow`添加倒是没问题）。我以为是自己的代码不对，下了个别人的样例发现也不生效。看了下还在experimental阶段，想了下算了呗。

**Comment by ivysrono** [comment]
storage API 第一次搞的时候怎么都不对，后来勉强试出来了也不明白为啥对。过了很久发现一些流行扩展也没用哈。

**Comment by jc3213** [comment]
![2](https://user-images.githubusercontent.com/8744936/120102676-b87a6080-c17e-11eb-93c2-55e1e7be5557.png)
把BT种子的文件改成这种呈现方式了，不知道比起原来的怎样？

**Comment by ivysrono** [comment]
还是没有用Aria2下载bt的习惯

**Comment by jc3213** [comment]
我只是想问直观观感哪个更改好，附带原版
![1](https://user-images.githubusercontent.com/8744936/120103009-1f4c4980-c180-11eb-91f9-63a3abc5eb55.png)

**Comment by ivysrono** [comment]
7那个文件名换行到头肯定不好看

**Comment by jc3213** [comment]
你意思是，如果不到头，跟序号岔开的话，还是 https://github.com/jc3213/download_with_aria2-firefox/issues/19#issuecomment-850985735 这个方式更好？

**Comment by jc3213** [comment]
![3](https://user-images.githubusercontent.com/8744936/120106285-04cd9c80-c18f-11eb-8308-e0785f844f6c.png)
比如这样？

**Comment by ivysrono** [comment]
这么说吧，按照标准，换行后的第一个字符应该跟 千 对齐，原版跟 7 对齐也不是大问题，新版都很夸张，不好看

**Comment by jc3213** [comment]
原版跟07对齐是因为文件名就包含`07. `而不是我生成的序号。另外我又进一步优化了主界面，让其更静态。这样应该能节省更多的性能。并且按照任务状态筛选也没出问题。不出意外的话，就是下一个版本了。

**Comment by ivysrono** [comment]
与其这样换行，不如限制显示长度，太长的文件名缩略，鼠标移上去再悬浮显示完整的

**Comment by jc3213** [comment]
我倒是想这么做，但是实现起来有BUG，下面的内容会覆盖上面的内容。很头疼……暂时不管了，我看了下昨天优化主界面的方法，任务只会按照先后顺序添加，准备改成新的active任务添加到第一个（目前也只能这么改）

**Comment by ivysrono** [comment]
无所谓啦，这个界面不是啥大问题

**Comment by jc3213** [comment]
我又做了一个

鼠标悬停前
![1](https://user-images.githubusercontent.com/8744936/120130590-24011400-c1f9-11eb-9b9e-52938580d164.png)

鼠标悬停后
![2](https://user-images.githubusercontent.com/8744936/120130602-28c5c800-c1f9-11eb-99e7-8100741e6fd2.png)

**Comment by ivysrono** [comment]
这个可以

**Comment by ivysrono** [comment]
这个可以

**Comment by jc3213** [comment]
测试了一下很长的就没救了……无解，保持原状吧

**Comment by jc3213** [comment]
如果可以的话帮忙测试一下master吧。我自己这边倒是没别的问题了，就是想优化`libs/ui/card.js`让在可滚动内容没到底或顶之前不翻页。但是不太会OTL
