### ISSUE TITLE
firefox r2100 with webRequest doesn't work

### ISSUE THREAD

**Issue by CrendKing** [jc3213/download_with_aria2-firefox#2]
Several issues:

1. `event.responseHeaders.filter(item => item.name === 'content-length')[0].value` missing a `.toLowerCase()`.

2. The `request` array seems out of synchronization. When returned to `fileSizeWrapper()`, the first element is never the one you pushed. It is always the jsonrpc URL, or a referrer URL, with wrong size.

**Comment by jc3213** [comment]
My work around is to record recent 15 entries of webRequest that have `Content-Length`  in response headers. 1. maybe typo, cause I've tried many approach, even `XHR`

Yes, the `request` array is out of sychronization. I've just try to get the `Content-Length` with `url` that matches `downloadItem.url`. I tested it on https://www.mozilla.org/en-US/firefox/all/#product-desktop-release try to download Firefox 81 or 82b2, it works fine though.

It's just an ugly try out, the XHR way should `cancel()` download, check for `Capturing`, create new download without prompt. Then there should be a list to confirm if the `url` must be ignored, or it will create download, then cancel it, dead loop. It's also rough, but seems better than `webRequest`?

**Comment by jc3213** [comment]
Here's the `XHR` version, have a try
[firefox r2100 with XHR.zip](https://github.com/jc3213/download_with_aria2-firefox/files/5275920/firefox.r2100.with.XHR.zip)

**Comment by CrendKing** [comment]
> Either of the approach may be buggy. I'd recommend it's better wait until Mozilla fixes it.

I'm all for waiting for proper API. No need for messy workaround (unless someone else asks for it, then it's up to you guys).

**Comment by jc3213** [comment]
Since XHR solution has been merged into `master` branch, the following discussion shoule be in #6
