### ISSUE TITLE
扩展名能否不区分大小写

### ISSUE THREAD

**Issue by RallyQ** [jc3213/download_with_aria2-firefox#20]
选项-基于条件-文件后缀中，添加了zip，但是网站的下载链接文件扩展名若是ZIP，这个扩展就无法识别抓取，文件后缀中必须再添加ZIP，才能抓取到
希望能不区分扩展名的大小写
谢谢！

**Comment by jc3213** [comment]
作为应急处理，你可以在`background.js`的第50行
https://github.com/jc3213/download_with_aria2-firefox/blob/f7b21515541ef90ede417d120709d44abe90591d/background.js#L50
将```item.filename.match(/[^\.]+$/)[0]```替换为```item.filename.match(/[^\.]+$/)[0].toLowerCase()```
即增加```.toLowerCase()```即可

**Comment by RallyQ** [comment]
火狐官方审核更新的扩展太慢？最新版本还是19天前的

**Comment by jc3213** [comment]
请参考 #19 我无法用自己的账号登录AMO，请参考里面的搬运，不好意思。
