### ISSUE TITLE
Unable to use the file size filter

### ISSUE THREAD

**Issue by lonelykid** [jc3213/download_with_aria2-firefox#22]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/2936633/120906016-0e8a5080-c624-11eb-8374-82b91f545909.png">
Thanks for providing this extension. I'm unable to set the file size filter

**Comment by lonelykid** [comment]
The only difference in UI I can find is 'MB' selector in a separate line. I do not use firefox userstyle. I don't think I have made any changes leading to that issue. I'm using a 13.3 MBP. But it's the same on my external monitor

**Comment by jc3213** [comment]
Since you are using MBP with MAC OS X, that may be a problem about font rendering.

 I will try to fix on my side, but I can't test for you cause I don't have MAC OS X running. You can change the `width` of `#sizeEntry` to fix the problem with usersyle.css though.

**Comment by lonelykid** [comment]
This extension can filter by filesize--at least for simple requests. Just use content-length

https://github.com/RossWang/Aria2-Integration/blob/8ffb9305e32394b275ded29fa197a479d2315285/App/common.js#L545

**Comment by jc3213** [comment]
That one uses `webRequest` to fileter downloads, and thus override Firefox default download prompt.

I'm using `downloads` API, but Firefox doesn't work as expected. I've tried to use both `webRequest` and `XMLHTTPRequest` to fix it my side, but they both came with other fatal issue that is not ready for common usage.
