### ISSUE TITLE
feature request: 自动清理已完成项目

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2-firefox#24]
可能需要自动清理的：
已完成项目
已失败项目

**Comment by jc3213** [comment]
已失败的项目暂时感觉不到清理的必要，尤其你需要知道错误的原因，或者可以转console？
已完成的项目理论是可以做清理的，但是做开关太麻烦。如果你有需要可以直接修改
https://github.com/jc3213/download_with_aria2-firefox/blob/ad72abd1305c38537c58045e1f3d4428a87102cb/popup/js.js#L74
增加```javascript
if (result.status === 'complete') {
    removeTaskFromQueue(result.gid, result.status) {
}```

**Comment by jc3213** [comment]
未来的目标
https://github.com/jc3213/download_with_aria2-chromium/issues/3

**Comment by jc3213** [comment]
目前已经迁移到了`storage` API，Chrome这边测试直接安装扩展会有一次报错。但是仅此一次（可以修复但是暂时不想）……同时做了向下兼容。我在Chrome端测试时没问题的。

后续就是调整`message`部分了？可以的话帮忙测试下最新的代码吧。我这边测试多半要晚上了

**Comment by ivysrono** [comment]
我在刷机……已经变砖售后了一次了……
现在总算成功进入系统了，就是不明白为啥有的时候要停用AVB验证，有的手机停用了就变砖不停用反而能刷第三方……

**Comment by jc3213** [comment]
哎，那就等晚上测试吧，我这边还在除虫

**Comment by jc3213** [comment]
火狐可真是个垃圾
https://github.com/jc3213/download_with_aria2-firefox/blob/f4dec7dae22ec077a53804e9ddcce96ed93969b7/components/main.js#L45
`browser.storage.sync.set(json)`直接报错，改成`browser.storage.local.set(json)`立刻工作。我吐了，吐得很难看。
然后options那边也改了。应该是OK了

**Comment by jc3213** [comment]
对于你要求的这个功能，我感觉有两套解决方案。假设选项为aria2RPC.options.jsonrpc.autoPurge，默认false，启用后true

1. 通过发送`aria2.purgeDownloadResult`请求来实现。但是这样的话需要修改修改`background.js`跟`/popup/js.js`两方面。background 35行 https://github.com/jc3213/download_with_aria2-firefox/blob/4ab465b455e5ce1a2cf046c73ae069785828f923/background.js#L35 判断 是否发起请求，popup做检测为 true 后不运行61行  https://github.com/jc3213/download_with_aria2-firefox/blob/4ab465b455e5ce1a2cf046c73ae069785828f923/popup/js.js#L61 生成已停止的菜单。

2. 在 popup 第75行前面检测 https://github.com/jc3213/download_with_aria2-firefox/blob/4ab465b455e5ce1a2cf046c73ae069785828f923/popup/js.js#L75 如果状态为 已终止 或 已完成 则单独发送清空这个任务的请求。

优缺点：
1. 第一个方案优点是性能最好，缺点是修改点比较多，并且`aria2.purgeDownloadResult`虽然会同时清理你提出的任务类别，但是对于只希望清理 已完成 的人来说不太合适？
2. 第二个方案修改点更少，并且更容易按类型进行处理，缺点是费性能。放在老版本单独发送jsonrpc的环境下还可以考虑。目前内部转发的前提下，感觉会吃掉更多的性能。

可行性：
如果你有需求可以fork这个repository。我也可以给你提供帮助（不管你选哪个方案）但我自己并不是特别愿意添加这个功能，更多的只是觉得点一下Purge按钮就好了

**Comment by jc3213** [comment]
我现在的目标还是移植到Manifest V3，通过修复控制台的错误log，同样的代码丢过去chrome版本后至少重启浏览器或者重新加载之前都还正常。点了重新加载或者重启浏览器后就开始抽风。关键看不到错误提示真的是谜之难受。

**Comment by jc3213** [comment]
另外我想表达的意思是，关于新功能的代码我会根据你需求的方案直接往你的repository里面推送。至于后续更新的话，你需要自己compare然后制作pull requests从我这边拉过去。

**Comment by ivysrono** [comment]
算啦，没啥必要。我可不想每天都不能保证的代码时间被更多常规工作占据……

**Comment by jc3213** [comment]
自动清理界面做好了，但是逻辑有点问题。如果做到后台，那么popup的任务栏的内容不会即时清理需要做message来传递信号再由popup这边来清理。做到popup的话只有打开popup时才会清理，而后台以然在累计。虽然只有在打开popup那一瞬间最消耗性能就是了。

**Comment by ivysrono** [comment]
一时都忘了怎么更新了……

**Comment by jc3213** [comment]
这里提供一下chromium版本的代码。除了UI跟options.json外一共要修改三处。popup 2处，background 1处。我的感觉是这个功能作用不大因此不考虑并入主线。
[Auto Purge Chromium.zip](https://github.com/jc3213/download_with_aria2-firefox/files/7112674/Auto.Purge.Chromium.zip)

**Comment by ivysrono** [comment]
Firefox不显示这个选项啊

**Comment by jc3213** [comment]
我只提供了chromium版本的diff文件。也就是修改了这些文件实现了这个功能，但是我感觉我能提供的方案都不太妥当。甚至我又想回到之前的message模式下了。至少还能更灵活。

**Comment by ivysrono** [comment]
> 
> 
> 自动清理界面做好了，但是逻辑有点问题。如果做到后台，那么popup的任务栏的内容不会即时清理需要做message来传递信号再由popup这边来清理。做到popup的话只有打开popup时才会清理，而后台以然在累计。虽然只有在打开popup那一瞬间最消耗性能就是了。
> 
> ![界面](https://user-images.githubusercontent.com/8744936/131594886-647ae9fe-513a-49f9-86c2-5363de852d44.png)

我以为这是在2.78提供了的意思。

**Comment by jc3213** [comment]
最简单的是你可以fork github上chromium的代码然后把这几个文件merge进去看看diff就知道修改什么了。

这个功能最大的缺陷就是交互，background发起purge请求，但是popup是无法接收的，除非用message通道进行传递。这样的话只能在popup写个判断来停止stopped任务生成界面，并且还要给停止按钮写个额外的判断。

一旦使用message通道，还不如全局又换回message通道再来处理其他的。但是之前那种方案不靠谱，因此再想到新方案之前无解。

**Comment by ivysrono** [comment]
没有就没有，关系不大

**Comment by jc3213** [comment]
开了个新repo，然后把两边的代码合并了。就是build时需要用到7z.exe，windows自带的tar.exe在压缩时有点问题

**Comment by ivysrono** [comment]
我一直在用 https://github.com/peazip/PeaZip/releases
等有空了看看build怎么优化兼容

**Comment by jc3213** [comment]
如果可以的话麻烦抽空发布一下新版吧……

另外请问一下用javascript怎么base64转码带有非拉丁字符的bittorrent文件？meta文件作为xml的变种，通过搜索到的方法利用`unescape(encodeURIComponent(STRING))`实现了，但是同样的操作用到torrent文件就抽风……就挺难受的……

**Comment by ivysrono** [comment]
原来是新库没有加入提醒。

不懂，太复杂了……

**Comment by jc3213** [comment]
我发现 FileReader API直接就能读取blob信息，出来就是base64编码……然后我还傻傻的读取text然后转码，我……现在解决了BT种子跟metalink，但是怎么实装是个问题，chromium可以直接拖到新建下载窗口，firefox则会自动关闭……

**Comment by ivysrono** [comment]
找到段代码，不知道解决的是不是你的问题
```
/** 解决 Fetch 直接输出的中文乱码问题
 * https://segmentfault.com/q/1010000004338890
 * https://blog.shovonhasan.com/using-promises-with-filereader/
 * @param {Binary} https://developer.mozilla.org/docs/Web/API/FileReader/readAsText
 * @return {String}
 */
const binary2Text = async (input) => {
  let reader = new FileReader();
  return new Promise((resolve, reject) => {
    reader.onerror = () => {
      reader.abort();
      reject(new DOMException('Problem parsing input.'));
    };
    reader.onload = () => {
      resolve(reader.result);
    };
    reader.readAsText(input);
  });
};
```

**Comment by jc3213** [comment]
我已经解决了torrent跟metalink，但是我尝试了2个实现方案，都不适合火狐。

------

方案1
======
1. 打开Popup，新建下载
2. 将torrent或者meta4, metalink文件拖拽到`下载链接`输入框

失败点： 火狐会在切换窗口（Alt + Tab）后进行点击时，自动关闭Popup导致无法拖拽。

方案2
======
1. 打开Popup，新建下载，按住Ctrl然后点击确认
2. 新建下载窗口发送信息给content_scripts，触发读取本地文件
3. 将读取结果发送给background，由background发起下载。

失败点：火狐不知道为什么，信息倒是成功传递了，但是读取文件没被正常触发，也就没后续的操作了……
