### ISSUE TITLE
通过webRequest设法解决`downloadItem.referrer`和`downloadItem.fileSize`的问题

### ISSUE THREAD

**Issue by jc3213** [jc3213/download_with_aria2-firefox#25]
根据`webRequest`记录的结果来看，或许我们完全可以不用使用`tabs`API来获取当前激活的标签页Url？这个记录同时还提供了cookie相关的`storeId`。感觉一劳永逸？

![webRequest](https://user-images.githubusercontent.com/8744936/123537204-d37dc780-d760-11eb-8f65-c1d50d8c03f8.png)

**Comment by jc3213** [comment]
@ivysrono 我在做更多的测试时找到了sourceforge无法下载的根本原因。是因为在执行fileSize wrapper的时候，item.url无法在记录中找到，导致出现`'size' of undefined`错误。
而事实是sourceforge本身就提供了`referrer`属性，偏偏没有文件大小，这是我测试不够多的原因，毕竟这个wrapper加进来就说了会不稳定。目前没有其他手段用来匹配。我先做个fix修复功能吧

**Comment by ivysrono** [comment]
R7010啥都下载不了了
![图片](https://user-images.githubusercontent.com/2649544/123542208-e604fa80-d77a-11eb-839a-85efd6e645e5.png)

**Comment by jc3213** [comment]
> R7010啥都下载不了了
> ![图片](https://user-images.githubusercontent.com/2649544/123542208-e604fa80-d77a-11eb-839a-85efd6e645e5.png)

麻烦尝试修改`Token`再改回来？因为我想减少代码量，把`token:`给塞入storage里面了。而老版本又是没有添加的。我在Chrome这边尝试升级没问题，火狐就不太清楚了。再就是火狐裸装的话也没问题（r7000测试）

**Comment by ivysrono** [comment]
在哪改？
R7000是不能抓取，不能下载的问题是R7010开始的。

**Comment by jc3213** [comment]
设置里面改，实在不行删除扩展重装吧。同样的方案chrome能解决问题firefox不能，有毒。我刚用的master做的测试结果
![2](https://user-images.githubusercontent.com/8744936/123546239-5701dd80-d78e-11eb-82a0-52dd14b3bc39.png)

**Comment by ivysrono** [comment]
简单卸载无用，需要清空扩展设置数据存储。在配置文件夹的哪里？

**Comment by jc3213** [comment]
试试打开debug控制台然后输入
```javascript
browser.storage.local.clear()
```
然后在输入
```javascript
fetch('option.json').then(response => response.json()).then(json => browser.storage.local.set(json))
```

**Comment by ivysrono** [comment]
好了，终于正常了

**Comment by jc3213** [comment]
> 好了，终于正常了

感觉把6900那个修复改成这个比较好。。。

**Comment by jc3213** [comment]
突然想起来asycrhonous function用fetch获取文件大小很简单。于是这么做了还真成功了，不过依然不推荐使用文件大小来筛选，尽量避免这个选项

这个功能可能导致任务先行下载（对磁盘进行I/O）然后取消并删除（依然对磁盘进行I/O），然后再开始下载。而优先级够高的筛选条件，`或许`能避免前面所述的情况（会发生这个情况都是火狐的下载事件的锅）
