### ISSUE TITLE
[Survy] Legacy version with latest changes? 是否有需要保留原来的旧框架？

### ISSUE THREAD

**Issue by jc3213** [jc3213/download_with_aria2-firefox#27]
The legacy version, which means version older than 2.6610, uses individual `jsonrpc.js` on each page `background`, `popup`, and modules of `popup`. Every page can send jsonrpc requests to aria2 JSON-RPC server on its own.

The legacy code workstream is:
1. The `background` keeps sending request every 1 second to indicate `Active` task numbers on toolbar badge
2. The `popup` sends request every 1 second to refresh details of each task in queue.
3. The `taskMgr` also do this every 1 second, too
4. There are other buttons that also send jsonrpc request once when clicked

The new code workstream is:
1. The `background` keeps sending request every 1 second to get all imformation that's needed and save them to `aria2RPC`
2. The `popup` use `connect` and `sendMessage` to retrive `aria2RPC`, and render the all tasks in queue
3. The `taskMgr` use `connect` and `sendMessage` to retrieve `aria2RPC`, and render the selected task details
4. The `message` interval can be set in `options` as `Refresh Interval`
5. There are other buttons that uses `sendMessage` to `background` then `background` send jsonrequest to `aria2c.exe`

The lagecy code has a light-weighted `background`, and also no delay when you click buttons to manage tasks. But it sends more jsonrpc requests to `aria2c.exe`, The new code have a relatively heavier `background`, it send only 1 jsonrpc request, but have delay, especially when you try to open `taskMgr`.

Which means **The legacy code has better performance if you just use it as a download tool. The new code has less jsonrpc requests that will ease the performance of `aria2c.exe`. They both may perform merely the same, if `popup` and `taskMgr` are all opened**

The lagacy code will send 3 jsonrpc request simultaneously every 1 second to contact with `aria2c.exe`, If you open `popup` and `taskMgr` together. And once error eccured while communicating with `aria2c.exe` - probably `Unauthorized` or `Not Found`, These requests will consume `aria2c.exe` and increase CPU usage significantly - 25% of a 4 core CPU, which means it ate up 1 CPU core.

The new structure - which was meant to be prepared for `Manifest V3` - I found it needed more CPU power, lack of interactivity, the most important thing is that, `background` freeze had not been fixed.

So I wonder if it is necessary to have a legacy version, with new changes like `storage` API, and `Refresh Interval`, or probably new `Auto Purge` for it?

**Comment by jc3213** [comment]
中文晚点更新

**Comment by jc3213** [comment]
@CrendKing @ivysrono @Mapaler

**Comment by CrendKing** [comment]
I'm sorry I'm currently not following the development process due to the Firefox file size bug. By reading your text (English and Chinese version) I don't understand why delegating all RPC to background would destroy interactivity and increase workload. If limiting the number of RPC is a global requirement (e.g. 1 request per second), then it doesn't matter how you structure your code, your user can only send one command once per second. If It is not a requirement, then sending request from 3 components or 1 component doesn't really matter, unless there is issue with concurrency.

**Comment by jc3213** [comment]
> I'm sorry I'm currently not following the development process due to the Firefox file size bug. By reading your text (English and Chinese version) I don't understand why delegating all RPC to background would destroy interactivity and increase workload. If limiting the number of RPC is a global requirement (e.g. 1 request per second), then it doesn't matter how you structure your code, your user can only send one command once per second. If It is not a requirement, then sending request from 3 components or 1 component doesn't really matter, unless there is issue with concurrency.

I just want to migrate to `Manifest V3` and have tried many different approach. This one works better than any other, but still, the `background` freezes at random condition without any notification - no logs in console or in `serviceworker-internals`

But during the development, I found some new possibility of old ones, and I want to have a try...

**Comment by Mapaler** [comment]
圈我我也看不懂的，完全业余人士。
控制Aria2我都是用专门的WebUI，扩展本身的还是不够用的。

**Comment by jc3213** [comment]
> 圈我我也看不懂的，完全业余人士。
> 控制Aria2我都是用专门的WebUI，扩展本身的还是不够用的。
Hmm， 如果是这样，我先考虑简化功能再说。OTL

**Comment by ivysrono** [comment]
https://github.com/mayswind/AriaNg/releases

**Comment by jc3213** [comment]
> https://github.com/mayswind/AriaNg/releases

我现在最大的问题是不UI，而是不知道为什么就是不兼容于`Manifest V3`，我只想一口锅丢给谷歌，然后躺平等更新了。

至于这个UI我已经很满意了OTL

**Comment by jc3213** [comment]
目前已经切换回了老框架，并且放弃抵抗了。

目前只能想到混合框架，background跟popup，options的交流可以试试用message，然后其他的JSON-RPC请求直接用jsonrpc.js感觉既能减少整体请求，又能满足交互性。但是一时半会懒得折腾了。太多东西积压，就这样吧。

**Comment by ivysrono** [comment]
R7500右键又失效了？

**Comment by jc3213** [comment]
抱歉，最近测试不过来了。太多东西积压了。我推测多半是因为之前反向没做好，应该是最开始是用`downWithAria2`然后改架构后成了`startDownload` => `downloadWithAria2`，多半是忘了改回来。
