### ISSUE TITLE
同名文件被自动覆盖无法自动重命名

### ISSUE THREAD

**Issue by RallyQ** [jc3213/download_with_aria2-firefox#28]
aria2默认会自动重命名同名文件，但是你这个扩展会自动覆盖同名文件，
aria2配置中增加了auto-file-renaming=true，通过你这个扩展的下载仍然会被自动覆盖，无法自动增加序号
而其他扩展会自动增加序号

**Comment by RallyQ** [comment]
再次测试，能自动重命名了

**Comment by jc3213** [comment]
> aria2默认会自动重命名同名文件，但是你这个扩展会自动覆盖同名文件，
> aria2配置中增加了auto-file-renaming=true，通过你这个扩展的下载仍然会被自动覆盖，无法自动增加序号
> 而其他扩展会自动增加序号

默认情况下我这边只提供了很少的设置，`auto-file-renaming`默认也是开启的，你下载不同链接的同名文件时也会自动在文件名后面增加序号（至少我的使用体验）
