### ISSUE TITLE
[BUG} 无法下载谷歌云盘文件

### ISSUE THREAD

**Issue by RallyQ** [jc3213/download_with_aria2-firefox#29]
## Platform
- Operation System: Windows 10
- Browser Firefox 89.0

一般文件下载正常，但是谷歌云盘文件无法下载，好像是cookies没传递到aria2中，其他扩展试了可以下载
请核实，谢谢！
如这个https://drive.google.com/file/d/1_NP_jkJ-FEjIMgiFra9ITmTVVWtTeGMn/view

**Comment by jc3213** [comment]
我在chromium版本下的测试结果为错误提示`Too many redirects: count=20`，cookie啥的倒是一切正常，晚点我用火狐版本测试一下

**Comment by RallyQ** [comment]
https://addons.mozilla.org/zh-CN/firefox/addon/aria2-integration/
https://addons.mozilla.org/zh-CN/firefox/addon/aria2-integration-extension/
这俩扩展都能正常下载

**Comment by jc3213** [comment]
> 对，也是这个错误提示
> https://addons.mozilla.org/zh-CN/firefox/addon/aria2-integration/
> https://addons.mozilla.org/zh-CN/firefox/addon/aria2-integration-extension/
> 这俩扩展都能正常下载

这两个扩展是右键菜单正常？还是抓取正常？理论上contextmenu的代码应该没太大区别啊？

**Comment by jc3213** [comment]
R7600已修复

**Comment by RallyQ** [comment]
> 
> 
> > 对，也是这个错误提示
> > https://addons.mozilla.org/zh-CN/firefox/addon/aria2-integration/
> > https://addons.mozilla.org/zh-CN/firefox/addon/aria2-integration-extension/
> > 这俩扩展都能正常下载
> 
> 这两个扩展是右键菜单正常？还是抓取正常？理论上contextmenu的代码应该没太大区别啊？
> 
> 试了下`Aria2 Download Manager Integration`，然后自己改了下代码， **测试发现获取cookie时使用下载用的url就能成功，而使用referer则会出错，提示跳转过多。** 那么解决方案就很简单了。更改cookie框架。
> 
> chromium版本修改后测试成功
> ![铬](https://user-images.githubusercontent.com/8744936/126022697-f533304c-7e19-4a87-85eb-52433730e9d1.png)

没用右键，都是直接点击，传递到aria2 rpc下载的

**Comment by RallyQ** [comment]
> 
> 
> R7600已修复，同时修复了R7400以来受到影响的cookieStoreId跟Folder相关功能

更新到新版，下载谷歌云盘正常了
感谢及时修复！
那俩扩展太臃肿，还是喜欢用你这个小巧的。

**Comment by jc3213** [comment]
> > R7600已修复，同时修复了R7400以来受到影响的cookieStoreId跟Folder相关功能
> 
> 更新到新版，下载谷歌云盘正常了
> 感谢及时修复！
> 那俩扩展太臃肿，还是喜欢用你这个小巧的。

他们臃肿主要是集成了Aria2Ng，我这个扩展功能简单，大概需要用到的功能都有。但是很多设置也不合理，你可以看我chrome版的readme，基本就是基于某个扩展的魔改（其实到现在基本算借鉴了界面跟基础框架的重写了）

最近我没时间也没思路去修改。比如火狐版之前转message port然后转回来，遗留了不少bug，也是最近有空了才开始修复。如果我没时间的话，可能你这个问题还要拖一段时间才能看得到。

还有比如全局aria2设置，还有taskMgr里面的任务设置，我都想改成有确定键跟取消键界面，确定后一次性的发送请求，这样修改多个任务选项后也不需要多次等任务重启。但是就是没时间……
