### ISSUE TITLE
Do not capture non-http downloads

### ISSUE THREAD

**Issue by CrendKing** [jc3213/download_with_aria2-firefox#4]
Some downloads have non-http URL. For example, some addons (e.g. FireMonkey) allow user to export config and script files by issuing a download. One example URL is `blob:moz-extension://2c5ef6dd-8aa5-4783-9f2f-ad73e8a6201b/989736d9-bfcd-43d5-84b6-298588f4690f`. When capture is enabled, these downloads are captured but can't be executed by aria2.

Can you add a check to capture for protocol (regardless of capture mode)?

**Comment by CrendKing** [comment]
Another example: download any directory with https://downgit.github.io. The URL is something like "blob:https://downgit.github.io/<some_guid>".

**Comment by jc3213** [comment]
It is because aria2 seems not support `blob`. at least it won't download a `blob` link

**Comment by CrendKing** [comment]
I know aria2 does not support blob. My suggestion is do not capture blob URL even user selects "Always" or "Built-in filter". Let Firefox handle it.

**Comment by jc3213** [comment]
> I know aria2 does not support blob. My suggestion is do not capture blob URL even user selects "Always" or "Built-in filter". Let browser handle it.

Sorry, I've misunderstand you...

I've met problems with `magnet` with many other aria2 browser extension with url check. they just check for `http` or `https`, while `ftp` and `magnet` is ignored and can't be download. That's why I'm writing this one.

Exception for `blob` is YES neccessary. I haven't met any `blob` schemes so I've forgotten this. Thanks for report

**Comment by CrendKing** [comment]
I agree `blob` is relatively rare, but it exists as a valid protocol that browser supports.

Another approach is instead of cancel the Firefox download right away then send the download to aria2, what about reverse the process, so that you only cancel Firefox download if `aria2.addUri` is sent without error. Otherwise, let Firefox handle that download. This way no matter what kind of incompatible URL that aria2 can't handle, or whatever reason aria2 can't download (e.g. aria2 can't preallocate disk space, etc.) user will always have a download.

The only problem of this approach is that since the RPC request is async, there is a little bit gap between the Firefox download starts and `aria2.addUri` returns. If the Firefox download is finished, then you have nothing to cancel, essentially user will have duplicate download. But 1. this should only have for extremely small files, which should be relatively rare, and 2. If the file size bug is fixed by Mozilla, #1 will no longer be problem.

**Comment by jc3213** [comment]
I've meant that you could just toggle the `Capturing` option when you met this problem as it is really rare case. It will be easy to bypass `blob` though. Add codes below to the head in the `onCreated` event code sections.
```if (item.url.startsWith('blob')) {
    return;
}````
