### ISSUE TITLE
Regression bug that download directory not passed through

### ISSUE THREAD

**Issue by CrendKing** [jc3213/download_with_aria2-firefox#5]
A recent commit https://github.com/jc3213/download_with_aria2-firefox/commit/c331760eb365111a6693c9fcd2684838b771eb53 changed the property key for download directory from "path" to "folder", but commit https://github.com/jc3213/download_with_aria2-firefox/commit/6da656d2dd8a041c48fc6666baf975835e2ec58a reverted the key name. As a result, now even I choose "Browser" for the "Download Folder" option it is still not passed through.

**Comment by jc3213** [comment]
Oops, that's a issue caused in https://github.com/jc3213/download_with_aria2-firefox/commit/33709864b528e4cf635f656c86582ce778a8d68b

It is because `session.path` is undefined for `contextmenu` or `capturing`
