### ISSUE TITLE
Duplicate download

### ISSUE THREAD

**Issue by CrendKing** [jc3213/download_with_aria2-firefox#6]
Hi. Found another bug, which is related to the file size of the download. I noticed when the target file is very small (e.g. around 1 MB) and I use always capture, I usually get duplicate download (aria2 is configured to never overwrite existing file). Try https://github.com/pbatard/rufus/releases/download/v3.11/rufus-3.11p.exe.

I debugged a bit, and found that when `downloads.onCreated()` is called for the small files, both `item.bytesReceived` and `item.totalBytes` are different, they are not 0 or -1. Examples:
```
byExtensionId: undefined
byExtensionName: undefined
bytesReceived: 1155640
canResume: false
danger: "safe"
endTime: null
error: null
estimatedEndTime: undefined
exists: false
fileSize: -1
filename: "C:\\rufus-3.11p.exe"
id: 13
incognito: false
mime: "application/octet-stream"
paused: false
referrer: null
startTime: "2020-10-09T13:35:03.233Z"
state: "in_progress"
totalBytes: 1155640
url: "https://github-production-release-asset-2e65be.s3.amazonaws.com/..."
```
Whereas for large files:
```
byExtensionId: undefined
byExtensionName: undefined
bytesReceived: 0
canResume: false
danger: "safe"
endTime: null
error: null
estimatedEndTime: undefined
exists: false
fileSize: -1
filename: "C:\\ubuntu-20.04.1-desktop-amd64.iso"
id: 14
incognito: false
mime: "application/x-iso9660-image"
paused: false
referrer: null
startTime: "2020-10-09T13:35:54.877Z"
state: "in_progress"
totalBytes: -1
url: "https://releases.ubuntu.com/20.04.1/ubuntu-20.04.1-desktop-amd64.iso"
```
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1666137, `totalBytes` is available after some download progress has achieved. Since it is not -1, and equals to `bytesReceived`, it means the download has completed. And the reason why `fileSize` is still -1 is maybe because it can only be available in `onChanged()`.

Anyway, I think you could add a check in `onCreated` event listener that if those fields are > 0 and equal, do not capture regardless of options, since the download is done.

**Comment by jc3213** [comment]
That's really shitty since Firefox triggers downloads altogether with `onCreated` event, while chromium doesn't. Which means when you see the download promt window, the download has already started in the background. Using `webRequest` is also another `nasty` way, kinda slow and not stable.

The possible work around is just pause the download, (but it still downloads in the background though) then do the check. cancel the downloads if `capturing` or resume it if not. Or cancel at first, do the check, restart if not matched (as #2 XHR way). The 2nd resolution is buggy, and will ask you to save the file twice. or downloads to `Default Download Folder` since `downloads.download` seems not passing download dir?

**Comment by jc3213** [comment]
try https://github.com/jc3213/download_with_aria2-firefox/commit/7bd6ad25135d9382f127b20197f7bd4eb66129ef

since https://github.com/jc3213/download_with_aria2-firefox/commit/c7ccec1f813a64ec36c8177abe64921c4ebfb5e4 uses old code in R2100

**Comment by CrendKing** [comment]
Thanks. The duplicate download problem is solved. But when I use the file size filter, the capture was correctly not activated, but the Firefox download is also canceled, so I end up having no download.

**Comment by jc3213** [comment]
Is there any link examples which is buggy for fileSize?

**Comment by CrendKing** [comment]
Just the same rufus file in my top comment. However, it seems the latest https://github.com/jc3213/download_with_aria2-firefox/commit/c50a265424dd08ed10902cef747def41aa0ba1ec fixed that problem. However, when downloading file over the file size filter, the capture does not work. Try https://releases.ubuntu.com/20.04.1/ubuntu-20.04.1-desktop-amd64.iso with 4 MB limit.

**Comment by jc3213** [comment]
There's a typo in c50a265 line 19
```
    var search = request.indexOf(item.url);
```
should be `requests`

**Comment by jc3213** [comment]
I've do some tests. It's because `localStorage` api stores key and value in strings. Chromium could match `string > string` or `integer > string`, while Firefox couldn't.

A quick fix up is ---- change line 80 in `background.js`
```
        var fileSize = (localStorage.getItem('fileSize') | 0);
```

**Comment by jc3213** [comment]
Please try the latest `master` branch

**Comment by CrendKing** [comment]
Excellent! Everything seems to be working.

**Comment by jc3213** [comment]
I've uploaded source codes without jQuery library.Although the codes are more light-weight, but they look dirty in my opinion. It's hard to maintain too. Wonder how you think about it?

**Comment by jc3213** [comment]
I meant here https://github.com/jc3213/download_with_aria2-firefox/releases/tag/2700 `no_jquery_src_r2700-firefox.zip`
I think jQuery is easy to access for my own, but not light-weight enough. and I think `document.querySelector` as well as `document.querySelectorAll` don't support multi selector as jQuery, some codes are really dirty if combined together.

**Comment by CrendKing** [comment]
Not know about your profession. But if you are young and passionate software developer, dropping jQuery would help you learn the language itself instead of always relying on scaffolding. Learning Javascript also opens up many other possibilities such as server development (Node), desktop application (Electron), type safe opportunities (Typescript) etc.

**Comment by jc3213** [comment]
I can write pure codes, but I don't like the way such as`document.querySelector` works. I'd prefer codes to be short and clear, while pure codes are long and complex. It's mostly my personal principle. Getting rid of `jQuery` frees up half of the file size, which is awesome too.

I'm planning to make it possible for bittorent download to toggle files to download using `aria2.changeOption`. But I don't have any clue to do that. It's hard to generate the file selection list as aria2 requires.

**Comment by CrendKing** [comment]
> my personal principle

Yes. The computer today is generally fast enough that there is no perceivable difference between raw DOM and jQuery. Mostly just personal taste, or say if you already familiar with one style, just keep using that style.

> bittorent download to toggle files

That is a bit more complex than what you have, but certainly doable. Frankly speaking, if I download BitTorrent, I'd use dedicated software to do it. If you introduce this feature, please add a disable button 😉 

> `innerHTML` with dynamic vairables

Sure, it is not idiomatic, but if the manipulated DOM tree is very complex, it is certainly cleaner.
