### ISSUE TITLE
Referrer domain instead of download URL domain for captured item?

### ISSUE THREAD

**Issue by CrendKing** [jc3213/download_with_aria2-firefox#7]
According to the code, if a download item does not have referrer, it uses the tab's URL as the referrer. Then during `captureCheck()`, the monitored/excluded domain is checked against the referrer, not the actual download URL. Why is it the case? I can see pros and cons for either side, but at least put some tooltip document for those two filters.

Also, since the query for tab is asynchronous, it is possible that user switches tab and end up getting a wrong referrer.

**Comment by CrendKing** [comment]
Also, even if the download matches an ignored domain, it still takes a while to trigger the download. Looks like it went through XHR to check the size. Shouldn't the XHR be skipped if you can already determine by domain?

**Comment by jc3213** [comment]
This is because most user can get the `item.finalUrl` in Chromium --Vivaldi I'm using don't show it but `item.referreror`. Or `item.url` in Firefox. Plus, it's much easier for user to get the domain of which download has been dispatched. This is the way this extension works.

I've add `item.fileSize` work around that way because I don't want to change the code too much from the `Chromium` one. I've got your suggestion. the `item.fileSize` override should work after the other three matching condition.

**Comment by CrendKing** [comment]
I understand the choice of using referrer. There could be case where multiple completely irrelevant sites link to same file that user wants to monitor/ignore, and end up having to put 100 entries instead of 1 into the box. But yes most of the time referrer is easier to use. I was confused at first. Maybe change the title to something like "Monitored/Ignored download page domain".

**Comment by jc3213** [comment]
I knew this potential issue which would happen for some file host...But mostly user won't switch to another tab if download is not started, and many file hosts have `captcha` to do human check...Only some software delivery sites will trigger downloads in a 3~15 second-period. The issue will occur if you switch to another sites `AND` there is no Referrer page is defined in `downloadItem`.

Matching domain from Download url has similar problem. some file hosts don't host in another hostname, or in a higher-level domain. for example,  downloads url from `aaa.com`  is `aaa.net/ccc.zip`(mozilla) or `cdn-aaa.com/bbb.zip`

**Comment by CrendKing** [comment]
> in a 3~15 second-period

It's one of the reasons I hate to use SourceForge, though I think they provide referrer. I even wrote user script myself to automate the redirection at the download page.

Feel free to close.

**Comment by jc3213** [comment]
I think I can do some optimization on `fileSize` work around though, I'll try to move it after the other three matching condition and have some test if it is worthy to do.

**Comment by jc3213** [comment]
The `item.fileSize` work around has been improved. I haven't test too much though
