### ISSUE TITLE
i18n fail?

### ISSUE THREAD

**Issue by CrendKing** [jc3213/download_with_aria2-firefox#8]
Just a kinda reminder that since the update of the recent i18n logic, the button text are broken since on my end. However, the options page still works. Guessing you didn't i18n that page?

BTW, the second screenshot is the options page taken from the addons page. If you watch closely, you can see the addon option pages have issue with margin-top or padding-top. The one in the popup was fine.

Firefox 83.0b2 English.

![1](https://user-images.githubusercontent.com/975235/96821293-6e592180-13dc-11eb-8827-d0958a523da9.jpg)
![2](https://user-images.githubusercontent.com/975235/96821294-6f8a4e80-13dc-11eb-8784-722817196623.jpg)

**Comment by jc3213** [comment]
Oops, my fault. only update the `modules/` folder

**Comment by jc3213** [comment]
fixed in https://github.com/jc3213/download_with_aria2-firefox/commit/2837d727c6d7a6c619293e669a7370180f090d68

**Comment by jc3213** [comment]
> BTW, the second screenshot is the options page taken from the addons page. If you watch closely, you can see the addon option pages have issue with margin-top or padding-top. The one in the popup was fine.

The problem has been fixed in https://github.com/jc3213/download_with_aria2-firefox/commit/939e402be7d6ee3e74f7b48f9e97796673b29960
It is weird that firefox doesn't automatically apply a `8px` margin on options page, while options on popup as an iframe has a `8px` margin.
