### ISSUE TITLE
Capture disrupts Firefox "Open with" function

### ISSUE THREAD

**Issue by CrendKing** [jc3213/download_with_aria2-firefox#9]
For example, if I download a zip, and ask Firefox to open it with 7-zip upon completion. Without the addon, it works as expected. However, if I use this addon with capture, even if I put the download domain to ignore, or file size less than the limit, 7-zip is never invoked to open the downloaded file.

I think it is because the capture wosks as

1) intercept download;
2) check condition. If false
3) create a new download in Firefox

The problem is that the "Open with" request is lost during step 3. I wonder if in step 1) you can save the request and pass through to step 3?

If not, I wonder if you can

1. Add "ignore extensions" option
2. Check ignored extensions and domains BEFORE intercepting download

**Comment by jc3213** [comment]
I'll look into it, but since I don't have much time recently, please be patient

**Comment by CrendKing** [comment]
Oh, no rush. Take your time.

**Comment by CrendKing** [comment]
Another related issue. Even if I disable the capture functionality, if I choose a save path during the prompt, the file is still downloaded to the default directory. It is if as the addon intercepted the request, found capture disabled, then add another fresh download request.

Take your time.

**Comment by jc3213** [comment]
> Another related issue. Even if I disable the capture functionality, if I choose a save path during the prompt, the file is still downloaded to the default directory.

This may be Firefox's problem with the download process and `downloads` API. I'll optimize the priority of `Capture` check to solve `this`, then try to fix the issue itself

**Comment by jc3213** [comment]
@CrendKing The issue should be fixed now, and I have to disable the `fileSize` work around...

Now I met some problem of `Content Security Policy` with popup inline `script-src`, I've tried all work around but they never work, I may have to revert the codes of buttons on popup

**Comment by CrendKing** [comment]
I guess we have to wait for Firefox' proper fix on the file size thingy. Thanks.
